routes:
  /rss/:
    template: rss
    content_type: text/xml
  /search/:
    template: search-results

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
